select * from employees;

select * from departments;


--LEFT OUTER
SELECT CUSTOMER_ID,FIRST_NAME,LAST_NAME,ADDRESS,PHONE
FROM CUSTOMER LEFT OUTER JOIN ADDRESS      --OUTER is optional ==> LEFT == LEFT OUTER
ON CUSTOMER.ADDRESS_ID = ADDRESS.ADDRESS_ID;

SELECT DEPARTMENT_NAME, STATE_PROVINCE
FROM DEPARTMENTS LEFT OUTER JOIN LOCATIONS
ON DEPARTMENTS.LOCATION_ID = LOCATIONS.LOCATION_ID ;

SELECT FIRST_NAME, START_DATE
FROM JOB_HISTORY LEFT OUTER JOIN EMPLOYEES
ON JOB_HISTORY.EMPLOYEE_ID = EMPLOYEES.EMPLOYEE_ID;

SELECT DEPARTMENT_NAME, END_DATE
FROM DEPARTMENTS D LEFT JOIN JOB_HISTORY J
ON D.DEPARTMENT_ID = J.JOB_ID;

SELECT E.JOB_ID, JOB_TITLE
FROM EMPLOYEES E LEFT JOIN JOBS J
ON E.JOB_ID = J.JOB_ID;

SELECT DEPARTMENT_NAME, END_DATE
FROM DEPARTMENTS LEFT JOIN JOB_HISTORY
ON DEPARTMENTS.DEPARTMENT_ID = JOB_HISTORY.DEPARTMENT_ID
WHERE END_DATE IS NOT NULL;

--RIGHT OUTER
SELECT CUSTOMER_ID,FIRST_NAME,LAST_NAME,ADDRESS,PHONE
FROM CUSTOMER RIGHT JOIN ADDRESS      --OUTER is optional ==> RIGHT == RIGHT OUTER
ON CUSTOMER.ADDRESS_ID = ADDRESS.ADDRESS_ID;

SELECT COUNTRY_NAME, C.REGION_ID
FROM COUNTRIES C RIGHT JOIN REGIONS R
ON C.REGION_ID = R.REGION_ID;

SELECT DEPARTMENT_NAME,COMMISSION_PCT
FROM EMPLOYEES E RIGHT JOIN  DEPARTMENTS D
ON D.MANAGER_ID = E.EMPLOYEE_ID
WHERE COMMISSION_PCT IS NOT NULL ;


SELECT FIRST_NAME, END_DATE
FROM EMPLOYEES RIGHT OUTER JOIN JOB_HISTORY
ON EMPLOYEES.EMPLOYEE_ID = JOB_HISTORY.EMPLOYEE_ID;

SELECT FIRST_NAME, JOB_TITLE
FROM EMPLOYEES RIGHT OUTER JOIN  JOBS
ON EMPLOYEES.JOB_ID = JOBS.JOB_ID
WHERE SALARY = MAX_SALARY;


--FULL OUTER
SELECT CUSTOMER_ID,FIRST_NAME,LAST_NAME,ADDRESS,PHONE
FROM CUSTOMER FULL JOIN ADDRESS      --OUTER is optional ==> FULL == FULL OUTER
ON CUSTOMER.ADDRESS_ID = ADDRESS.ADDRESS_ID;

SELECT REGION_ID, COUNTRY_NAME
FROM REGIONS FULL JOIN COUNTRIES
ON REGIONS.REGION_ID = COUNTRIES.REGION_ID;

SELECT FIRST_NAME, START_DATE, END_DATE
FROM EMPLOYEES FULL JOIN JOB_HISTORY
ON EMPLOYEES.EMPLOYEE_ID = JOB_HISTORY.EMPLOYEE_ID;



