select * from employees;

select * from departments;


--LEFT OUTER
SELECT CUSTOMER_ID,FIRST_NAME,LAST_NAME,ADDRESS,PHONE
FROM CUSTOMER LEFT OUTER JOIN ADDRESS      --OUTER is optional ==> LEFT == LEFT OUTER
                              ON CUSTOMER.ADDRESS_ID = ADDRESS.ADDRESS_ID;

--RIGHT OUTER
SELECT CUSTOMER_ID,FIRST_NAME,LAST_NAME,ADDRESS,PHONE
FROM CUSTOMER RIGHT JOIN ADDRESS      --OUTER is optional ==> RIGHT == RIGHT OUTER
                         ON CUSTOMER.ADDRESS_ID = ADDRESS.ADDRESS_ID;

--FULL OUTER
SELECT CUSTOMER_ID,FIRST_NAME,LAST_NAME,ADDRESS,PHONE
FROM CUSTOMER FULL JOIN ADDRESS      --OUTER is optional ==> FULL == FULL OUTER
                        ON CUSTOMER.ADDRESS_ID = ADDRESS.ADDRESS_ID;