--get me all employees first_name,last_name and their managers first and lastname
SELECT *
FROM EMPLOYEES;


SELECT EMPLOYEE_ID,FIRST_NAME,LAST_NAME,MANAGER_ID
FROM EMPLOYEES;

--SELF JOIN
SELECT E1.EMPLOYEE_ID,E1.FIRST_NAME,E1.LAST_NAME,E1.MANAGER_ID,E2.EMPLOYEE_ID,E2.FIRST_NAME,E2.LAST_NAME
FROM EMPLOYEES E1 JOIN EMPLOYEES E2
ON E1.MANAGER_ID = E2.EMPLOYEE_ID
ORDER BY E1.EMPLOYEE_ID;