--get me first_name,last_name and department name for all employees
SELECT *
FROM EMPLOYEES;

SELECT *
FROM DEPARTMENTS;

SELECT *
FROM LOCATIONS;

SELECT *
FROM COUNTRIES;

SELECT FIRST_NAME,LAST_NAME,DEPARTMENT_NAME
FROM EMPLOYEES E LEFT JOIN DEPARTMENTS D
ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
WHERE E.DEPARTMENT_ID IS NULL;

--get me first_name,last_name and department_name,city for all employees
SELECT FIRST_NAME,LAST_NAME,DEPARTMENT_NAME, CITY
FROM EMPLOYEES E JOIN  DEPARTMENTS D
ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
JOIN LOCATIONS L
ON D.LOCATION_ID = L.LOCATION_ID;

--get me firstname,lastname and department name, city,country_name for all employees;
SELECT FIRST_NAME,LAST_NAME,DEPARTMENT_NAME, CITY,COUNTRY_NAME
FROM EMPLOYEES E JOIN  DEPARTMENTS D
ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
JOIN LOCATIONS L
ON D.LOCATION_ID = L.LOCATION_ID
JOIN COUNTRIES C
ON L.COUNTRY_ID = C.COUNTRY_ID;