SELECT DISTINCT JOB_ID
FROM EMPLOYEES;

SELECT AVG(SALARY)
FROM EMPLOYEES
WHERE JOB_ID IN ('IT_PROG');

SELECT AVG(SALARY)
FROM EMPLOYEES
WHERE JOB_ID IN ('IT_PROG');

SELECT JOB_ID, AVG(SALARY)
FROM EMPLOYEES
GROUP BY JOB_ID;

SELECT JOB_ID, AVG(SALARY), COUNT(*), SUM(SALARY)
FROM EMPLOYEES
GROUP BY JOB_ID;

SELECT JOB_ID, AVG(SALARY), COUNT(*), SUM(SALARY)
FROM EMPLOYEES
GROUP BY JOB_ID
HAVING AVG(SALARY) > 5000;


