SELECT * FROM EMPLOYEES;
-- reads all column from employees table

SELECT * FROM DEPARTMENTS;
-- reads all column from departments table

SELECT FIRST_NAME FROM EMPLOYEES;
-- reads FIRST_NAME from departments table

select CITY from LOCATIONS;
-- reads CITY names from locations table

select FIRST_NAME, LAST_NAME, SALARY from EMPLOYEES;
-- reads FIRST_NAME, LAST_NAME, SALARY from locations table

SELECT STREET_ADDRESS, POSTAL_CODE FROM LOCATIONS;
-- reads STREET_ADDRESS, POSTAL_CODE from locations table

SELECT DISTINCT FIRST_NAME FROM EMPLOYEES;
-- remove duplicates

SELECT * FROM EMPLOYEES, DEPARTMENTS;

SELECT EMPLOYEES.EMPLOYEE_ID, DEPARTMENTS.DEPARTMENT_ID FROM EMPLOYEES, DEPARTMENTS;

SELECT * FROM EMPLOYEES
WHERE SALARY = (SELECT MAX(SALARY) FROM EMPLOYEES);

